//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gpucaster.rc
//
#define IDC_MYICON                      2
#define IDCANCEL2                       3
#define IDCANCEL3                       4
#define IDCANCEL4                       5
#define IDCANCEL5                       6
#define IDCANCEL6                       7
#define IDCANCEL8                       9
#define IDCANCEL9                       10
#define IDCANCEL10                      11
#define IDD_GPUCASTER_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_GPUCASTER                   107
#define IDI_SMALL                       108
#define IDC_GPUCASTER                   109
#define IDR_MAINFRAME                   128
#define IDD_SETTINGS                    129
#define IDD_LIGHTING                    130
#define IDD_GPGPU_CTRL                  131
#define IDD_GET_STRING                  135
#define IDC_SEED                        1000
#define IDC_FRACTAL                     1001
#define IDC_MS                          1002
#define IDC_PREWARP                     1003
#define IDC_NOISE_TYPE                  1004
#define IDC_PRIM_BOX                    1005
#define IDC_R1                          1005
#define IDC_NOISE_TYPE2                 1005
#define IDC_LIGHTN_R                    1005
#define IDC_PRIM_SPHERE                 1006
#define IDC_G1                          1006
#define IDC_NOISE_TYPE3                 1006
#define IDC_LIGHTN_G                    1006
#define IDC_PRIM_PLANE                  1007
#define IDC_B1                          1007
#define IDC_NOISE_TYPE4                 1007
#define IDC_LIGHTN_B                    1007
#define IDC_PRIM_TORUS                  1008
#define IDC_WRAP1                       1008
#define IDC_LIGHTN_WRAP                 1008
#define IDC_PRIM_CYL                    1009
#define IDC_NOISE_TYPE5                 1009
#define IDC_FOG_R                       1009
#define IDC_PRIM_PYR                    1010
#define IDC_R2                          1010
#define IDC_FOG_G                       1010
#define IDC_PRIM_REPEAT                 1011
#define IDC_G2                          1011
#define IDC_FOG_B                       1011
#define IDC_NOISE_WAVELEN               1012
#define IDC_B2                          1012
#define IDC_FOG_DENSITY                 1012
#define IDC_NOISE_AMP                   1013
#define IDC_WRAP2                       1013
#define IDC_FOG_EXP                     1013
#define IDC_PREWARP_WRINKLES            1014
#define IDC_PREWARP_WAVELEN             1015
#define IDC_R3                          1015
#define IDC_PREWARP_AMP                 1016
#define IDC_G3                          1016
#define IDC_PREWARP_WRINKLE_FREQ        1017
#define IDC_B3                          1017
#define IDC_PREWARP_WRINKLE_AMP         1018
#define IDC_WRAP3                       1018
#define IDC_PRIM_SERP                   1019
#define IDC_FOV                         1020
#define IDC_SPEC_STR                    1020
#define IDC_ZF                          1021
#define IDC_SPEC_EXP                    1021
#define IDC_AMBO_LO                     1022
#define IDC_AMBO_HI                     1023
#define IDC_AMBO_EXP                    1024
#define IDC_BRIGHTNESS                  1025
#define IDC_RAND_COL_1                  1026
#define IDC_LIGHTN_RAND_COL             1026
#define IDC_RAND_DIR_1                  1027
#define IDC_STATUS                      1027
#define IDC_LIGHTN_RAND_DIR             1027
#define IDC_RAND_ALL_1                  1028
#define IDC_LIGHTN_RAND_ALL             1028
#define IDC_RAND_COL_2                  1029
#define IDC_SATURATION                  1029
#define IDC_RAND_DIR_2                  1030
#define IDC_LIGHTN_EDIT_COL             1030
#define IDC_RAND_ALL_2                  1031
#define IDC_AMBO_DIR_SCALE              1031
#define IDC_RAND_COL_3                  1032
#define IDC_AMBO_DIR_BIAS               1032
#define IDC_RAND_DIR_3                  1033
#define IDC_AMBO_SPEC_LO                1033
#define IDC_RAND_ALL_3                  1034
#define IDC_RAND_ALL_LIGHTS             1034
#define IDC_RAND_SPEC                   1035
#define IDC_RAND_AMBO                   1036
#define IDC_SELECT_1                    1037
#define IDC_IMPORT                      1037
#define IDC_SELECT_2                    1038
#define IDC_EXPORT                      1038
#define IDC_SELECT_3                    1039
#define IDC_AMBO_SPEC_HI                1039
#define IDC_LIGHT_NAME                  1040
#define IDC_LIGHT0_COLOR_PREVIEW        1041
#define IDC_LIGHT1_COLOR_PREVIEW        1042
#define IDC_LIGHT2_COLOR_PREVIEW        1043
#define IDC_LIGHT3_COLOR_PREVIEW        1044
#define IDC_LIGHT_DESC0                 1045
#define IDC_LIGHT_DESC1                 1046
#define IDC_LIGHT_DESC2                 1047
#define IDC_LIGHT_DESC3                 1048
#define IDC_ROTATE_ALL_LIGHTS           1049
#define IDC_IMPORT3                     1050
#define IDC_MOUSE_CAMERA                1050
#define IDC_LIGHTN_COL_PREVIEW          1051
#define IDC_LIGHTN_BSPEC                1052
#define IDC_LIGHT4_COLOR_PREVIEW        1053
#define IDC_LIGHT_DESC4                 1054
#define IDC_AMBO_BDIR                   1055
#define IDC_CLOSE                       1056
#define IDC_TEXT                        1056
#define IDC_FOG_RAND_COLOR              1057
#define IDC_PROMPT                      1057
#define IDC_FOG_RAND_ALL                1058
#define IDC_TEXT2                       1058
#define IDC_FOG_COLOR_PREVIEW           1059
#define IDC_TEXT3                       1059
#define IDC_REFL                        1060
#define IDC_TEXT4                       1060
#define IDC_LIGHT_NAME2                 1061
#define IDC_TEXT5                       1061
#define IDC_SURF_COLOR_AMT              1062
#define IDC_LABEL1                      1062
#define IDC_EVAL1                       1063
#define IDC_LABEL2                      1063
#define IDC_EVAL2                       1064
#define IDC_LABEL3                      1064
#define IDC_EVAL3                       1065
#define IDC_LABEL4                      1065
#define IDC_LABEL5                      1066
#define IDC_IMPORT2                     1066
#define IDC_IMPORT_ALL                  1066
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
